sudo: false

language: python

python:
    - "2.7"

install:
    # Install conda
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --yes conda

    # Install dependencies
    - conda env create --name bfd --file environment.yml
    - source activate bfd

script:
    - flake8
